name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand
  workflow_dispatch:
  push:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "::set-output name=modified::true"
        continue-on-error: true
      - name: lint on diff
        if: steps.git-check.outputs.modified == 'true'
        uses: ./github/workflows/lint.yml
      - name: run tests on diff
        if: steps.git-check.outputs.modified == 'true'
        uses: ./github/workflows/test.yml
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
